name: getwidget
description: GetWidget is open source library that come with pre-build 1000+ UI components. It makes development faster & more enjoyable. You can customize the component as per your need.
version: 2.0.2
homepage: https://github.com/ionicfirebaseapp/getwidget

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_datagrid: ^19.1.69-beta
  syncfusion_flutter_core: ^19.1.69

  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
